baseURL = 'https://d0n4t3ll0-64.github.io/cyber-whats-public/'
languageCode = 'en-us'
title = 'Cyber Whats'
theme = 'hello-friend-ng'
paginate = 10

[params]
  dateform = "Jan 2, 2006"
  dateformShort = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  backgroundImage = "/bg-1.jpg"
  enableThemeToggle = true
 
  # Subtitle for home
  homeSubtitle = "Find what you need.. Hack what you want..."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  [permalinks]
  posts = "/posts/:year/:title/"

  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
     logoCursorColor    = "#1BDA5E"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"
    # Append the current url pathname to logoText 
    # logoCursorPathname = true


  [params.portrait]
     path     = "/whats-logo.png"
     alt      = "Portrait"
     maxWidth = "100px"

  [params.footer]
    trademark = 2024
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by d0n4t3ll0"
    ]

  [languages]
    [languages.en.params.logo]
      logoText = "Cyber WHats"
      logoHomeLink = ""

[[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

[[menu.main]]
    identifier = "tools"
    name       = "Tools"
    url        = "/tools"

[[menu.main]]
    identifier = "news"
    name       = "Cyber News"
    url        = "/news"